version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - postgres.env

  redis:
    image: redis:alpine
    restart: unless-stopped

  app:
    #image: nextcloud:fpm-alpine
    build: ./app
    restart: unless-stopped
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    env_file:
      - postgres.env
    depends_on:
      - postgres
      - redis

  nextcloud:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nextcloud:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  cron:
    #image: nextcloud:fpm-alpine
	build: ./app
    restart: unless-stopped
    volumes:
      - ./nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - postgres
      - redis

